name: MLflow CI/CD Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    env:
      # Token DagsHub (Dari Secrets)
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      
      # Username DagsHub
      MLFLOW_TRACKING_USERNAME: "NurusSafaah"
      
      # Password MLflow adalah Token DagsHub
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub pandas scikit-learn matplotlib seaborn

    - name: Run MLflow Project
      run: |
        # Jalankan project yang ada di dalam folder MLProject
        mlflow run MLProject --env-manager=local 

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        # Setup nama image
        IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/telco-churn-project:latest
        
        # Buat Dockerfile manual untuk membungkus hasil kerja
        echo "FROM python:3.9-slim" > Dockerfile
        echo "WORKDIR /app" >> Dockerfile
        
        # Copy isi folder MLProject ke dalam image
        echo "COPY MLProject/ ." >> Dockerfile
        
        # Install library
        echo "RUN pip install pandas scikit-learn mlflow dagshub matplotlib seaborn" >> Dockerfile
        
        # Perintah jalan
        echo "CMD [\"python\", \"modelling.py\"]" >> Dockerfile
        
        # Build & Push
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
        echo "âœ… Sukses Push ke Docker Hub!"